name: Build documentation

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'Writerside/all'
  DOCKER_VERSION: '2025.04.8412'
  IS_GROUP: 'true'  # Uncomment to build a group
  FOLDER_TO_FLATTEN: 'artifacts/WritersideDeployTest'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      algolia_artifact: ${{ steps.define-ids.outputs.algolia_artifact }}
      artifact: ${{ steps.define-ids.outputs.artifact }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define instance id and artifacts
        id: define-ids
        run: |
          INSTANCE=${INSTANCE#*/}
          INSTANCE_ID_UPPER=$(echo "$INSTANCE" | tr '[:lower:]' '[:upper:]')
          ARTIFACT="webHelp${INSTANCE_ID_UPPER}2-all.zip"
          ALGOLIA_ARTIFACT="algolia-indexes-${INSTANCE_ID_UPPER}.zip"

          # Print the values
          echo "INSTANCE_ID_UPPER: $INSTANCE_ID_UPPER"
          echo "ARTIFACT: $ARTIFACT"
          echo "ALGOLIA_ARTIFACT: $ALGOLIA_ARTIFACT"

          # Set the environment variables and outputs
          echo "INSTANCE_ID_UPPER=$INSTANCE_ID_UPPER" >> $GITHUB_ENV
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
          echo "ALGOLIA_ARTIFACT=$ALGOLIA_ARTIFACT" >> $GITHUB_ENV
          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
          echo "algolia_artifact=$ALGOLIA_ARTIFACT" >> $GITHUB_OUTPUT

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          docker-version: ${{ env.DOCKER_VERSION }}
          is-group: ${{ env.IS_GROUP }}
          artifact: ${{ steps.define-ids.outputs.artifact }}

      - name: Flatten folder structure
        run: |
          # Find the ZIP that starts with webHelp
          ZIP_FILE=$(find artifacts -type f -name "webHelp*.zip" | head -n 1)

          if [ -z "$ZIP_FILE" ]; then
            echo "No ZIP file found starting with webHelp"
            exit 1
          fi

          echo "Processing ZIP: $ZIP_FILE"

          # Create a temporary folder
          TMP_DIR=$(mktemp -d)

          # Extract the ZIP into temp folder
          unzip -qq "$ZIP_FILE" -d "$TMP_DIR"

          # Find the first directory inside the extracted folder
          FIRST_DIR=$(find "$TMP_DIR" -mindepth 1 -maxdepth 1 -type d | head -n 1)

          if [ -z "$FIRST_DIR" ]; then
            echo "No directory found inside ZIP"
            exit 1
          fi

          echo "Flattening directory: $FIRST_DIR"

          # Move all contents to the root of TMP_DIR
          mv "$FIRST_DIR"/* "$TMP_DIR"/

          # Remove the original directory
          rmdir "$FIRST_DIR"

          # Create a new ZIP in a temporary file
          TEMP_ZIP=$(mktemp --suffix=.zip)
          cd "$TMP_DIR"
          zip -r -qq "$TEMP_ZIP" ./*

          # Replace the original ZIP with the new flattened ZIP
          mv "$TEMP_ZIP" "$GITHUB_WORKSPACE/$ZIP_FILE"

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: artifacts/*
          retention-days: 7
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq "artifacts/${{ needs.build.outputs.artifact }}" -d dir

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4